### ISSUE TITLE
RL crashes with speedruntools loaded and adjusting game speed in custom training

### ISSUE THREAD

**Issue by NitrOP7674** [ianwillis98/SpeedrunTools#5]
Let me know if you need any help reproducing this.  I don't think I have done any customization of speedruntools' settings (or even used it yet to be honest).

EDIT: game speed is adjusted using the standard bakkesmod "game speed" slider.

**Comment by easypercent** [comment]
Will be fixed in next update. Disable SpeedrunTools if you need to adjust gravity slider in the mean time

**Comment by purtzel2020** [comment]
i want a plugin that i can see all players in the match with alpha boost

can you program that?

**Comment by easypercent** [comment]
> i want a plugin that i can see all players in the match with alpha boost
> 
> can you program that?

Not allowed by Psyonix. 

https://bakkesmod.fandom.com/wiki/Commonly_Requested_Features#Having_Other_Players_See_your_Bakkesmod_items
